### ISSUE TITLE
Add for loop example

### ISSUE THREAD

**Issue by mrdoomus** [mrdoomus/cohort70-python#1]
# Description

A new python file called `for_loop.py` needs to be created.
It must containg a for loop example in python with comments explaining every line of code.

**Comment by Fidelnieto** [comment]
What do you want me to loop?

**Comment by mrdoomus** [comment]
@Fidelnieto 

I want you to loop the letters of the abecedary and print them on the screen.

**Comment by Fidelnieto** [comment]
@mrdoomus got it!
